### ISSUE TITLE
send_fax_notifications and send_voicemail_notifications fail to run

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#115]
both send_fax_notifications and send_voicemail_notifications fail to run via cron:

```
From gs5@localhost.localdomain  Fri Jan 18 15:39:33 2013
Return-Path: <gs5@localhost.localdomain>
X-Original-To: gs5
Delivered-To: gs5@localhost.localdomain
Received: by localhost.localdomain (Postfix, from userid 998)
        id A2C82F1A94; Fri, 18 Jan 2013 15:39:33 +0100 (CET)
From: root@localhost.localdomain (Cron Daemon)
To: gs5@localhost.localdomain
Subject: Cron <gs5@gs5> ( sleep 30; cd /opt/gemeinschaft; bundle exec rake send_fax_notifications ) (failed)
Content-Type: text/plain; charset=UTF-8
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <SHELL=/var/lib/gemeinschaft/.rvm/bin/rvm-shell>
X-Cron-Env: <RAILS_ENV=development>
X-Cron-Env: <HOME=/var/lib/gs5>
X-Cron-Env: <LOGNAME=gs5>
Message-Id: <20130118143933.A2C82F1A94@localhost.localdomain>
Date: Fri, 18 Jan 2013 15:39:33 +0100 (CET)

rake aborted!
Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs/runtimes.rb:51:in `autodetect'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-rails-3.2.2/lib/coffee-rails.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
/opt/GS5/config/application.rb:7:in `<top (required)>'
/opt/GS5/Rakefile:5:in `require'
/opt/GS5/Rakefile:5:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)
```

```
From gs5@localhost.localdomain  Fri Jan 18 15:40:03 2013
Return-Path: <gs5@localhost.localdomain>
X-Original-To: gs5
Delivered-To: gs5@localhost.localdomain
Received: by localhost.localdomain (Postfix, from userid 998)
        id 70EA4F1A94; Fri, 18 Jan 2013 15:40:03 +0100 (CET)
From: root@localhost.localdomain (Cron Daemon)
To: gs5@localhost.localdomain
Subject: Cron <gs5@gs5> ( cd /opt/gemeinschaft; bundle exec rake send_voicemail_notifications ) (failed)
Content-Type: text/plain; charset=UTF-8
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <SHELL=/var/lib/gemeinschaft/.rvm/bin/rvm-shell>
X-Cron-Env: <RAILS_ENV=development>
X-Cron-Env: <HOME=/var/lib/gs5>
X-Cron-Env: <LOGNAME=gs5>
Message-Id: <20130118144003.70EA4F1A94@localhost.localdomain>
Date: Fri, 18 Jan 2013 15:40:03 +0100 (CET)

rake aborted!
Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs/runtimes.rb:51:in `autodetect'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/execjs-1.4.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/coffee-rails-3.2.2/lib/coffee-rails.rb:1:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `block in require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362@global/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
/opt/GS5/config/application.rb:7:in `<top (required)>'
/opt/GS5/Rakefile:5:in `require'
/opt/GS5/Rakefile:5:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)
```

However running `bundle exec rake send_voicemail_notifications` resp. `bundle exec rake send_fax_notifications` as user gs5 does not show any errors.
I have no idea what is going wrong here :-/

**Comment by jpawlowski** [comment]
seems to be related to nodejs which is not in the PATH for the cron jobs.
Should be fixed by https://github.com/amooma/GBE/commit/ee0a5ed3dce8f890107eb70df7247f262b5dd881
