### ISSUE TITLE
undefined method to move higher/lower in call routes

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#121]
```
NoMethodError (undefined method `move_higher' for nil:NilClass):
  app/controllers/call_routes_controller.rb:52:in `move_higher'



NoMethodError (undefined method `move_lower' for nil:NilClass):
  app/controllers/call_routes_controller.rb:57:in `move_lower'

```

**Comment by wintermeyer** [comment]
Fixed in a6779c0
