### ISSUE TITLE
GEM installation error

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#175]
New builds show this error:

```

GBE: Install GS gems ...

Fetching gem metadata from http://rubygems.org/.......
Fetching gem metadata from http://rubygems.org/..
Fetching git://github.com/plataformatec/simple_form.git
 [31mUnfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
 [0m/var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler.rb:294:in `block in load_gemspec_uncached': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler.rb:291:in `chdir'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler.rb:291:in `load_gemspec_uncached'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler.rb:282:in `load_gemspec'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:411:in `block in load_spec_files'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:410:in `each'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:410:in `load_spec_files'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:799:in `load_spec_files'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:381:in `local_specs'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/source.rb:774:in `specs'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/lazy_specification.rb:53:in `__materialize__'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/spec_set.rb:86:in `block in materialize'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/spec_set.rb:83:in `map!'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/spec_set.rb:83:in `materialize'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/definition.rb:113:in `specs'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/definition.rb:108:in `resolve_remotely!'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/installer.rb:81:in `run'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/installer.rb:14:in `install'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/cli.rb:230:in `install'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/vendor/thor/task.rb:27:in `run'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/vendor/thor.rb:275:in `dispatch'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/vendor/thor/base.rb:408:in `start'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/bin/bundle:14:in `block in <top (required)>'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/lib/bundler/friendly_errors.rb:4:in `with_friendly_errors'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/gems/bundler-1.2.3/bin/bundle:14:in `<top (required)>'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/bin/bundle:19:in `load'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385@global/bin/bundle:19:in `<main>'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
        from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by wintermeyer** [comment]
@kuroir Do you have an idea what this could be? It seems to be in context of the simple_form gem.

**Comment by jpawlowski** [comment]
I guess this needs to be corrected somehow:
https://github.com/amooma/GS5/commit/964c81fc615b35c9ee909a47901f307be6ce2c3a

**Comment by wintermeyer** [comment]
The error message says:
`invalid byte sequence in US-ASCII (ArgumentError)`
It looks like it is because of a lack of declaration of encoding on the gemspec file.

Let's see if a9bf3a7 works as a work around.

**Comment by jpawlowski** [comment]
yep, seems to be working again.
