### ISSUE TITLE
db:migrations fail with utf8

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#21]
IN the latest production build migrations fail once again:

```
Wed Dec 19 15:15:14 2012: ** Invoke db:migrate (first_time)
Wed Dec 19 15:15:14 2012: ** Invoke environment (first_time)
Wed Dec 19 15:15:14 2012: ** Execute environment
Wed Dec 19 15:15:18 2012: ** Invoke db:load_config (first_time)
Wed Dec 19 15:15:18 2012: ** Invoke rails_env (first_time)
Wed Dec 19 15:15:18 2012: ** Execute rails_env
Wed Dec 19 15:15:18 2012: ** Execute db:load_config
Wed Dec 19 15:15:18 2012: ** Execute db:migrate
Wed Dec 19 15:15:18 2012: rake aborted!
Wed Dec 19 15:15:18 2012: An error has occurred, all later migrations canceled:
Wed Dec 19 15:15:18 2012: 
Wed Dec 19 15:15:18 2012: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `uuindex` ON `channels` (`uuid`, `hostname`)
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `block in execute'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:344:in `add_index'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:450:in `block in method_missing'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:424:in `block in say_with_time'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:424:in `say_with_time'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:444:in `method_missing'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:334:in `method_missing'
Wed Dec 19 15:15:18 2012: /opt/GS5/db/migrate/20111104140900_create_channels.rb:35:in `up'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:358:in `up'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:396:in `block (2 levels) in migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:396:in `block in migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:118:in `with_connection'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:377:in `migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:512:in `migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:704:in `block (2 levels) in migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:761:in `call'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:761:in `ddl_transaction'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:703:in `block in migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:684:in `each'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:684:in `migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:554:in `up'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/migration.rb:535:in `migrate'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.2/lib/active_record/railties/databases.rake:153:in `block (2 levels) in <top (required)>'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/bin/rake:19:in `load'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/bin/rake:19:in `<main>'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
Wed Dec 19 15:15:18 2012: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
Wed Dec 19 15:15:18 2012: Tasks: TOP => db:migrate
```

Question: Is it okay to create the gemeinschaft db with utf8 settings instead of latin1?
This is something I added yesterday in https://github.com/GS5-build/GBE/commit/9e56751d917e60d46db5a71ada2904e8ae8c8271

**Comment by jpawlowski** [comment]
temporal fix with https://github.com/GS5-build/GBE/commit/75d84d67429f96baf3768162006b6e465067163a
(as it's still unclear why UTF8 cannot be used by default)
