### ISSUE TITLE
Backup failed  after clean install

### ISSUE THREAD

**Issue by matis2le** [amooma/GS5#216]
URL which triggered the bugreport is: /tenants/2
GS5 buildname: 1302281156 (5.1.0)

Please provide your bugreport below this line and update the title of this issue to a more specific one.
- Backup triggered after install failed all times
- Folder /var/backup/gs5 stays empty
- klicking on "view" gives an error page

**Comment by wintermeyer** [comment]
Please provide a screenshot of http://ip.address/backup_jobs

**Comment by matis2le** [comment]
![backup_jobs](https://f.cloud.github.com/assets/3501879/207227/70cef756-81e9-11e2-83b4-fdecec5767c3.JPG)

**Comment by matis2le** [comment]
Bei einer weiteren Neuinstallation auf Hardware das gleiche Ergebnis... Ich nutze grundsätzlich die Option mit Text und fester IP. Auch ein Warten von 24h hat nix geändert. (falls es noch irgendwelche Jobs gibt die vorher durchlaufen müssten)  
Gib es irgendein Log was ich zur Unterstützung liefern kann?

**Comment by matis2le** [comment]
hab das Log gefunden:

/var/lib/gs5/Backup/log/backup.log

[2013/03/03 13:23:00][message] Performing Backup for 'GS5 backup (GS5)'!
[2013/03/03 13:23:00][message] [ backup 3.0.27 : ruby 1.9.3p392 (2013-02-22 revision 39386) [i686-linux] ]
[2013/03/03 13:23:00][message] Database::MySQL started dumping and archiving 'gemeinschaft'.
[2013/03/03 13:23:00][message] Using Compressor::Gzip for compression.
[2013/03/03 13:23:00][message]   Command: '/bin/gzip'
[2013/03/03 13:23:00][message]   Ext: '.gz'
[2013/03/03 13:23:01][message] Database::MySQL Complete!
[2013/03/03 13:23:01][message] Backup::Archive has started archiving:
[2013/03/03 13:23:01][message] Using Compressor::Gzip for compression.
[2013/03/03 13:23:01][message]   Command: '/bin/gzip'
[2013/03/03 13:23:01][message]   Ext: '.gz'
[2013/03/03 13:23:01][error] ModelError: Backup for GS5 backup (GS5) Failed!
[2013/03/03 13:23:01][error]   An Error occured which has caused this Backup to abort before completion.
[2013/03/03 13:23:01][error]   Reason: Archive::PipelineError
[2013/03/03 13:23:01][error]   Failed to Create Backup Archive
[2013/03/03 13:23:01][error]   Pipeline STDERR Messages:
[2013/03/03 13:23:01][error](Note: may be interleaved if multiple commands returned error messages)
[2013/03/03 13:23:01][error]  
[2013/03/03 13:23:01][error]   /bin/tar: Anlegen eines leeren Archivs wird feige verweigert.
[2013/03/03 13:23:01][error]   „/bin/tar --help“ oder „/bin/tar --usage“ gibt weitere Informationen.
[2013/03/03 13:23:01][error]   The following system errors were returned:
[2013/03/03 13:23:01][error]   Error: Errno::ENOENT: No such file or directory - 'tar' returned exit code: 2
[2013/03/03 13:23:01][error] 
[2013/03/03 13:23:01][error] Backtrace:
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/archive.rb:94:in `perform!'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/model.rb:254:in`each'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/model.rb:254:in `block in perform!'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/model.rb:252:in`each'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/model.rb:252:in `perform!'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/cli/utility.rb:74:in`block in perform'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/cli/utility.rb:65:in `each'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/lib/backup/cli/utility.rb:65:in`perform'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.17.0/lib/thor/invocation.rb:120:in`invoke_task'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thor-0.17.0/lib/thor/base.rb:434:in`start'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/backup-3.0.27/bin/backup:11:in `<top (required)>'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/backup:19:in`load'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/backup:19:in `<main>'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in`eval'
[2013/03/03 13:23:01][error]   /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
[2013/03/03 13:23:01][warning] CleanerError: Cleanup Warning
[2013/03/03 13:23:01][warning]   The temporary backup folder still contains files!
[2013/03/03 13:23:01][warning]   '/var/lib/gs5/Backup/.tmp/GS5'
[2013/03/03 13:23:01][warning]   This folder may contain completed Archives and/or Database backups.
[2013/03/03 13:23:01][warning]  
[2013/03/03 13:23:01][warning]   Make sure you check these files before the next scheduled backup for
[2013/03/03 13:23:01][warning]   'GS5 backup (GS5)'
[2013/03/03 13:23:01][warning]   These files will be removed at that time!
[2013/03/03 13:23:01][message] ModelError: If you have other Backup jobs (triggers) configured to run,
[2013/03/03 13:23:01][message]   Backup will now attempt to continue...

**Comment by wintermeyer** [comment]
Die Zeile 
`/bin/tar: Anlegen eines leeren Archivs wird feige verweigert.`
ist der Schlüssel. Es sind in dem System entweder keine Voicemails oder keine Avatarbilder enthalten. Deshalb jammert tar rum. Ich schaue es mir an.

**Comment by matis2le** [comment]
hab sowohl ein Avatarbild als auch eine Voicemail erzeugt - leider unverändert!

**Comment by wintermeyer** [comment]
Fixed by 75362f4
