### ISSUE TITLE
private_pub/faye error

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#237]
As I was just doing some debugging I thought you might be interested in this (in the hope that it will be useful for you):

```
192.168.6.108 - - [11/Mar/2013 14:48:42] "GET /faye.js HTTP/1.1" 304 - 0.0012
Rack::Lint::LintError: Status must be >=100 seen as integer
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:19:in `assert'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:425:in `check_status'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:50:in `_call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/chunked.rb:43:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:41:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:45:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:137:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/bin/rackup:4:in `<top (required)>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `load'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `<main>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
192.168.6.108 - - [11/Mar/2013 14:48:42] "GET /faye HTTP/1.1" 500 134497 0.0501
Rack::Lint::LintError: Status must be >=100 seen as integer
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:19:in `assert'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:425:in `check_status'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:50:in `_call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/chunked.rb:43:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:41:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:45:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:137:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/bin/rackup:4:in `<top (required)>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `load'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `<main>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
192.168.6.108 - - [11/Mar/2013 14:48:42] "GET /faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fhandshake%22%2C%22version%22%3A%221.0%22%2C%22supportedConnectionTypes%22%3A%5B%22callback-polling%22%5D%2C%22id%22%3A%221%22%7D%5D&jsonp=__jsonp1__ HTTP/1.1" 500 73813 0.0257
Rack::Lint::LintError: Status must be >=100 seen as integer
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:19:in `assert'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:425:in `check_status'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:50:in `_call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/chunked.rb:43:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:41:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:45:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:137:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/bin/rackup:4:in `<top (required)>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `load'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `<main>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
192.168.6.108 - - [11/Mar/2013 14:48:42] "GET /faye HTTP/1.1" 500 134671 0.0442
Rack::Lint::LintError: Status must be >=100 seen as integer
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:19:in `assert'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:425:in `check_status'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:50:in `_call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/chunked.rb:43:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:41:in `process'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/faye-websocket-0.4.7/lib/faye/adapters/thin.rb:45:in `receive_data'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:137:in `start'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/bin/rackup:4:in `<top (required)>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `load'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/rackup:19:in `<main>'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
192.168.6.108 - - [11/Mar/2013 14:48:42] "GET /faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fsubscribe%22%2C%22clientId%22%3A%221vvkpl4khepw0arrarde8vp2tzyi4sb%22%2C%22subscription%22%3A%22%2Fusers%2F1%2Fmessages%2Fnew%22%2C%22id%22%3A%222%22%2C%22ext%22%3A%7B%22private_pub_signature%22%3A%221343070777ebbfec96f59fbd5281b47ea2a8ba57%22%2C%22private_pub_timestamp%22%3A1363009721136%7D%7D%2C%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%221vvkpl4khepw0arrarde8vp2tzyi4sb%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%223%22%2C%22advice%22%3A%7B%22timeout%22%3A0%7D%7D%5D&jsonp=__jsonp2__ HTTP/1.1" 500 75802 0.0321


```

**Comment by wintermeyer** [comment]
It seems that is should always be started in production mode.
https://github.com/ryanb/private_pub/issues/30
https://github.com/faye/faye/issues/25

**Comment by jpawlowski** [comment]
Hm but I don't get any logs when running in production mode to debug correct functioning. this is a mismatch... ;(

**Comment by wintermeyer** [comment]
https://github.com/faye/faye/issues/25#issuecomment-375678

production mode is the only way to do this.

**Comment by aashishgarg** [comment]
why it's only run on production Env
