### ISSUE TITLE
uninitialized constant CacheDigests (NameError)

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#314]
```
uninitialized constant CacheDigests (NameError)
  /opt/GS5/config/environments/development.rb:17:in `block in <top (required)>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:24:in `class_eval'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:24:in `configure'
  /opt/GS5/config/environments/development.rb:1:in `<top (required)>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/engine.rb:571:in `block in <class:Engine>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /opt/GS5/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/passenger/helper-scripts/rack-preloader.rb:82:in `eval'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/passenger/helper-scripts/rack-preloader.rb:82:in `preload_app'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/passenger/helper-scripts/rack-preloader.rb:127:in `<module:App>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/passenger/helper-scripts/rack-preloader.rb:6:in `<module:PhusionPassenger>'
  /var/lib/gs5/.rvm/gems/ruby-2.0.0-p247/gems/passenger/helper-scripts/rack-preloader.rb:5:in `<main>'
```

**Comment by jpawlowski** [comment]
http://pastebin.com/3QB4e7hu
