### ISSUE TITLE
db:migrate issue "undefined method `entity' for #<GsParameter:0xadfb380>"

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#79]
db:migrate currently fails with following errors:

```
==  CreateGsParameters: migrating =============================================
-- create_table(:gs_parameters)
   -> 0.0008s
==  CreateGsParameters: migrated (0.0009s) ====================================

==  PopulateGsParameterWithDefaults: migrating ================================
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `entity' for #<GsParameter:0xadfb380>
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/attribute_methods.rb:407:in `method_missing'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/attribute_methods.rb:148:in `method_missing'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations/uniqueness.rb:29:in `block in validate_each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations/uniqueness.rb:28:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations/uniqueness.rb:28:in `validate_each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validator.rb:153:in `block in validate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validator.rb:150:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validator.rb:150:in `validate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:310:in `_callback_before_23'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:418:in `_run__292649513__validate__835033881__callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validations.rb:212:in `run_validations!'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:425:in `_run__292649513__validation__835033881__callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activemodel-3.2.2/lib/active_model/validations.rb:179:in `valid?'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations.rb:69:in `valid?'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations.rb:77:in `perform_validations'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/validations.rb:50:in `save'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:241:in `block in save'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/transactions.rb:240:in `save'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/persistence.rb:45:in `create'
/opt/GS5/db/migrate/20130105120353_populate_gs_parameter_with_defaults.rb:5:in `up'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:396:in `block (2 levels) in migrate'
/var/lib/gs5/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:396:in `block in migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:118:in `with_connection'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:377:in `migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:512:in `migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:704:in `block (2 levels) in migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:761:in `call'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:761:in `ddl_transaction'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:703:in `block in migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:684:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:684:in `migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:554:in `up'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/migration.rb:535:in `migrate'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/railties/databases.rake:153:in `block (2 levels) in <top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/var/lib/gs5/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/rake:19:in `load'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/rake:19:in `<main>'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
/var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by jpawlowski** [comment]
fixed with 9c15b1dfd6057cbfde8c6a5c8d90a35073ec5dca
